### ISSUE TITLE
The creative mode inventory of the mod is empty with multiconnect-1.6-beta.12

### ISSUE THREAD

**Issue by Cccc-owo** [FireMuffin303/WildFirefly#2]
Just like the title.
With [multiconnect-1.6-beta.12](https://github.com/Earthcomputer/multiconnect/releases/tag/v1.6-beta.12):
![image](https://user-images.githubusercontent.com/47687154/172805590-bce104ae-9103-4c35-909f-0eaba3ec14c8.png)
Without [multiconnect-1.6-beta.12](https://github.com/Earthcomputer/multiconnect/releases/tag/v1.6-beta.12):
![image](https://user-images.githubusercontent.com/47687154/172805982-ba642cd1-4f08-478e-8d2b-74b218cb41c9.png)

**Comment by FireMuffin303** [comment]
I have been checked on this. It's seem this bug was occurred by multiconnect-1.6-beta.12 instead, since I see no error on testing and I have been tried with few other mods that add items which got the same issue.
